[package]
name = "bevy_city"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { path = "../../../", features = [
  "https",
  "free_camera",
  "experimental_bevy_feathers",
] }

argh = "0.1"
noise = "0.9.0"
rand = "0.10.0"
